"""empty message

Revision ID: 7bc73151b583
Revises: 9cfd590a2493
Create Date: 2020-07-10 15:08:03.819000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7bc73151b583'
down_revision = '9cfd590a2493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'encrypted_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_password', mysql.VARCHAR(length=93), nullable=False))
    # ### end Alembic commands ###
